### ISSUE TITLE
key-6.dat PBES2 формат

### ISSUE THREAD

**Issue by vedmak02** [dstucrypt/signerbox2#11]
Добрій день, отримали ключі в податковій(key-6.dat + key-11.dat), перевірили на державних сервісах ключі працюють. При спробі використати ключі на signerbox2 отримуємо помилку
![image](https://user-images.githubusercontent.com/14543297/88049312-96c34c80-cb5d-11ea-8c5b-ca8f8b599051.png)
Більше детально перевіривши, знайшли що файл розшифровується як файл формату PBES2
![image](https://user-images.githubusercontent.com/14543297/88057522-df353700-cb6a-11ea-881b-d4027a77aa48.png)

Пробували розшифрували ключ за допомогою методу jkurwa.models.Priv.from_protected, але отримуємо помилку Failed to decode tag of "0" at: ["attr"] при декодуванні. Якщо вказати невірний пароль то помилка інша, тому скоріш за все пароль правильний і правильно формує data в from_protected, але при формуванні пакету з ключами Priv.from_asn1(data, true) не може правильно декодувати на DstuPrivkey.decode(data, 'der');

Можу надати ключ для перевірки кейсу.

**Comment by muromec** [comment]
>Пробували розшифрували ключ за допомогою методу jkurwa.models.Priv.from_protected, але отримуємо помилку Failed to decode tag of "0" at: ["attr"] при декодуванні. 

а покажіть трейсбек.

**Comment by vedmak02** [comment]
Failed to decode tag of "0" at: ["attr"]
    at DecoderBuffer.error (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/reporter.js:78:11)
    at DecoderBuffer.readUInt8 (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/buffer.js:66:17)
    at derDecodeTag (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/decoders/der.js:273:17)
    at DERNode.decodeTag [as _decodeTag] (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/decoders/der.js:54:22)
    at DERNode.decode [as _decode] (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:341:25)
    at decodeChildren (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:378:15)
    at Array.forEach (<anonymous>)
    at DERNode.decode [as _decode] (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:375:22)
    at DERNode.decode [as _decode] (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:280:47)
    at Generated.decode (/home/admin/web/test.com.ua/public_html/node/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/decoders/der.js:28:20)

**Comment by muromec** [comment]
пришліть ключ з паролем на ilya.muromec@gmail.com

**Comment by vedmak02** [comment]
Відправив тестовий ключ(сформований через https://acskidd.gov.ua/keys-generation) та пароль, помилка повторюється ідентична бойовому ключу

**Comment by vedmak02** [comment]
Для швидкого повторення помилки:
var key = fs.readFileSync(__dirname + '/sign/TestKey-6.dat')
var password = 'TestTest';
try {   
    var keyDataSigned = jkurwa.models.Priv.from_protected(key, password, gost89.compat.algos());
} catch (e) {
    console.log(['keyDataSigned error', e]);
}
try {  
    password = 'WrongPassword';
    var keyDataWrongPass = jkurwa.models.Priv.from_protected(key, password, gost89.compat.algos());
} catch (e) {
    console.log(['keyDataWrongPass error', e]);
}

**Comment by muromec** [comment]
Спробуйте, чи працює з цим патчем:

```
diff --git a/lib/models/Priv.js b/lib/models/Priv.js
index 654721b..6731575 100644
--- a/lib/models/Priv.js
+++ b/lib/models/Priv.js
@@ -90,7 +90,7 @@ var from_asn1 = function (data, return_store) {
         return key0;
     }
 
-    key1 = attr_parse(priv.attr);
+    key1 = priv.attr && attr_parse(priv.attr);
     return {
         keys: key1 ? [key0, key1] : [key0],
         format: "privkeys",
diff --git a/lib/spec/keystore.js b/lib/spec/keystore.js
index b1ed28e..13ae135 100644
--- a/lib/spec/keystore.js
+++ b/lib/spec/keystore.js
@@ -97,7 +97,7 @@ var DstuPrivkey = asn1.define('DstuPrivkey', function () {
             )
         ),
         this.key('param_d').octstr(),
-        this.key('attr').implicit(0).seqof(KeyAttr)
+        this.key('attr').optional().implicit(0).seqof(KeyAttr)
     );
 });

```

**Comment by vedmak02** [comment]
Так, формує ключ формату privkeys, перевіряю далі, дякую 
на сайті signerbox2 треба доповнити метод flattenMaterial, т.я. на даному етапі приходить файл формату PBES2 і його не хендлить. Ще раз дякую.

**Comment by muromec** [comment]
Оновив 1f238dee -- подивіться на сайті чи працює з живим ключем

**Comment by vedmak02** [comment]
Ні, після вибору key-6.dat файлу не переходу до eтапу з вводом паролю, повторюється як на тестовому так і на бойовому ключі, неможливо перевірити виправлений етап, т.я. немає можливості ввести пароль.

**Comment by muromec** [comment]
От зараз точно працює

**Comment by vedmak02** [comment]
Так, тепер можна ввести пароль, але після вводу пароля не переходить до підпису файла.
![image](https://user-images.githubusercontent.com/14543297/88109618-83db6700-cbb3-11ea-92e3-15386bc193c6.png)
Скоріше за все не знаходить сертифікат від податкової
const URLS = [
  'http://masterkey.ua/services/cmp/',
  'https://ca.informjust.ua/services/cmp/',
];

Треба додати acskidd.gov.ua

**Comment by muromec** [comment]
окей, додав

**Comment by vedmak02** [comment]
Тепер працює чітко, файл підписало, перевірив на https://czo.gov.ua/verify - файл підписаний коректно.

**Comment by muromec** [comment]
топ
